"%bitmex":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        bitmex-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.bitmex.deserializer.BitmexDeserializer


"%binance":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        binance-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.binance.deserializer.BinanceDeserializer


"%bitstamp":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        bitstamp-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.bitstamp.deserializer.BitstampDeserializer


"%coinbase":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        coinbase-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.coinbase.deserializer.CoinbaseDeserializer


"%kraken":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        kraken-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.kraken.deserializer.KrakenDeserializer


"%all":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        kraken-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.all.deserializer.TickerDeserializer
        coinbase-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.all.deserializer.TickerDeserializer
        bitstamp-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.all.deserializer.TickerDeserializer
        binance-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.all.deserializer.TickerDeserializer
        bitmex-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.all.deserializer.TickerDeserializer