"%bitmex":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        bitmex-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer


"%binance":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        binance-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer


"%bitstamp":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        bitstamp-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer


"%coinbase":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        coinbase-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer


"%kraken":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        kraken-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer


"%all":
  kafka:
    bootstrap:
      servers: localhost:9092
  mp:
    messaging:
      incoming:
        kraken-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer
        coinbase-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer
        bitstamp-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer
        binance-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer
        bitmex-data-feed:
          connector: smallrye-kafka
          value:
            deserializer: de.kpi.worker.kafka.consumer.deserializer.TickerDeserializer